# Don't change this
theme: jekyll-theme-primer

# AMWA ID
amwa_id: AS-11_X1

# GitHub project
baseurl: /AS-11_X1

# Which release or branch appears in header links and on the home page
default_tree: branches/master

# Regex patterns of tags (releases) and branches to show
show_tags: 
show_branches: master

# So we can redirect from e.g. /is-04
plugins:
  - jekyll-redirect-from
